### ISSUE TITLE
Migrate from CoffeeScript to ES2015

### ISSUE THREAD

**Issue by thardy** [liquid-lang/liquid-node#47]
I'm finding myself needing a lot of functionality not provided yet in liquid-node, namely:
- Layouts
- Blocks/Sections
- Ability to pass data to includes

Currently, I'm implementing these features outside of your module, by pre-processing the template strings before I pass them to liquid-node.  I would gladly help implement these features if liquid-node was not written in CoffeeScript.  I can't stand whitespace-sensitive languages.  I remember you saying that the primary reason you went with CoffeeScript was due to liquid being in Ruby and CoffeeScript having a much better class implementation.  

Well, now that ES6/EcmaScript2015 is supported natively in Node (and it's super easy to use a preprocessor like Babel otherwise), would you consider making the switch?  I would gladly take the time I'm spending implementing these features outside of your module and implement them inside instead.  I think you'd easily triple the potential contributors to your project as well.  There are a ton more people willing to contribute to pure javascript projects than there are to CoffeeScript projects.

Let me know because I am working on the above features, just not in CoffeeScript.  Regardless, I will point you to my finished work when I'm done.  You'll be welcome to integrate the changes from mine if you like.

**Comment by sirlantis** [comment]
Hey @thardy - yes, I think it would be great to switch to ES6 now that it has most of CoffeeScript's features.

One thing that would need validation first though is whether we get decent Regex interpolation (which really makes reading and combining those expressions much easier) - I don't know about the state of template strings in ES6. (http://www.2ality.com/2012/12/template-strings-xregexp.html)

- [ ] Try if `decaffeinate` does a good first pass
- [ ] Find out about template strings for regular expressions

**Comment by cameronroe** [comment]
+1 for ES2015

**Comment by jayands** [comment]
I've forked the code to [work on this](/jayands/liquid-node/tree/esnext/), but I have some questions:

- Are you trying to *just* stick to ES2015? If we use Babel, there are plugins ([`stage-0`][babel-stage-0], [`env`][babel-env]) that let us take advantage of the latest (and future) specs, including (if anyone else can grok it; I'm having trouble learning) true `async`/`await` functions
- Do you want active type analysis? Babel can strip it out, but I'm curious if it should stay in comments or if I can actually put the types in the "open", so to speak.
- What minimum Node would you be looking to target? The current LTS is 6, but it would *also* make sense to target 4, instead
- Is it okay if I make some "radical" changes? Some of the objects that you have look like [`Map`s][mdn-map] or their [weak][mdn-weakmap] counterparts, and I think that they'd benefit from being such. Combined with `flow`-based static analysis this may become `this.filters: Map<string, Function> = StandardFilters.entries()..fiter(([name,func]) => func != null).forEach( ([filterName, filter]) => {/*...*/})`, for example 
- Is it okay to use external libraries? I understand that it might not have existed modularly at the time, but Lodash's [`range`][lodash.range] seems like a near-perfect drop-in replacement for `Range`, as an example. If you want the actual *class*, just wrap it around a variable that uses it internally or something.
- Do you want me to finish conversion before submitting a PR?
- Do you want me to keep the CoffeeScript in the codebase when I *do* submit a PR?
- Do you want to keep the code looking "similar"? I'm using [`eslint-config-standard`][eslint-config-standard] for that exact reason, but I *personally* think that [Airbnb's config][eslint-config-airbnb-base] provides stricter code

And finally:

- All of the above applicable questions, but with [TypeScript][typescript] instead?

[eslint-config-standard]: https://github.com/feross/eslint-config-standard
[eslint-config-airbnb-base]: https://github.com/airbnb/javascript
[lodash.range]: https://www.npmjs.com/package/lodash.range
[babel-env]: https://babeljs.io/docs/plugins/preset-env/
[babel-stage-0]: https://babeljs.io/docs/plugins/preset-stage-0/ 
[mdn-map]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
[mdn-weakmap]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap
[typescript]: https://www.typescriptlang.org/docs/home.html

**Comment by sirlantis** [comment]
Hey @jayands, thanks for pushing this!

You raise a bunch of great points.

- It think Babel and ES6 is a great choice, but TypeScript seems great, too. My personal preference would actually be towards TypeScript, but I'd leave that up to you.
- Node v6 seems a sensible lower bound.
- Radical changes also make sense. When I wrote this project back then, I kind of copied Ruby code and punched it until it compiled with CoffeeScript. Things like using Map sounds great.
- External libraries are okay.
- Feel free to submit a WIP PR if you mark it as WIP.
- Feel free to nuke CoffeeScript into orbit.
- Strict linter rules sound great. Airbnb sounds like a decent candidate. I'm personally not a big fan of semicolons and single quotes over double quotes, but I'm fine with what your take on it is.

Let me know if there's anything else!

**Comment by jayands** [comment]
Thanks so much for responding! I had actually forked the code _again_, this time as a completely local copy with the git folder restarted, to work on it _in_ TypeScript and then I was going to bring the "fixed" code back to JS (nearly all TS is _also_ valid Flow code, haha; only a few keywords need to be stripped out, mostly just the access keywords) but take full advantage of VS Code as an IDE in the meantime.

Furthermore, it turns out `async`/`await` are _much_ easier than any site tried to explain them before the Egghead.io course, because they were also trying to explain generators at the same time and all manner of extra confusion. So at least there's that.

**Comment by aleclarson** [comment]
It's worth noting that https://github.com/harttle/shopify-liquid exists.

**Comment by zeke** [comment]
The coffeescript to JavaScript migration happened a while ago in this PR: https://github.com/liquid-lang/liquid-node/pull/71 🎉
