### ISSUE TITLE
Transfer repo to an organization

### ISSUE THREAD

**Issue by zeke** [liquid-lang/liquid-node#73]
To ensure a long and happy life for the `liquid` (nee `liquid-node`) npm package, let's move the repository to an organization. This will allow multiple open source community members to share the responsibility of maintaining it.

@sirlantis I've invited you to be an owner of a new org: https://github.com/liquid-lang -- if you're okay with this idea, feel free to go ahead and transfer the repo there.

Thanks!

**Comment by big-kahuna-burger** [comment]
To be closed?

**Comment by zeke** [comment]
Yep!
