### ISSUE TITLE
Keep the duble curly braces if variable is null or undefined

### ISSUE THREAD

**Issue by GustavoRPS** [liquid-lang/liquid-node#79]
```
let Liquid = require('liquid')
templateEngine = new Liquid.Engine()

templateEngine
  .parse('Hello {{ my_variable }}')
  .then(template => {
    return template.render(null)
    // return template.render({})
  })
  .then(result => {
    console.log(result)
    // Return:
    // Hello 
    // Expected:
    // Hello {{ my_variable }}
  })
```

**Comment by zeke** [comment]
I don't think this use case is likely to be supported. Not sure what you're trying to accomplish, but you may want to use conditionals and `raw` tags to preserve some Liquid expressions in your output in the case where a value is falsy: https://shopify.github.io/liquid/tags/raw/

**Comment by GustavoRPS** [comment]
@zeke thanks for the suggestion  but I not trying to keep as `raw`.

It's simple what I'm trying to accomplish:
- I have a `{{ variable_tag }}`
- I have a `object` without the `variable_tag` attribute/property
- Wen I execute `template.render(object)` I want that the `{{ variable_tag }}` still there
- But the `{{ variable_tag }}` is replace with `null` value and gone when is rendered

So basic I suggesting to have a default behavior of instead replacing the `{{ variable_tag }}` "nothing" keep the `{{ variable_tag }}` there to know that something is missing or to reuse to another purpose.


Fo  now I doing like this `var object = { variable_tag = '{{ variable_tag }}' }` to keep the `tag` there if not have a value to the variable.

**Comment by zeke** [comment]
I think you should change your approach to validating the data. Rather than relying on a different visible value in the template, you should check the values in the object first, before rendering. If you're using Node.js, you can do something like this:

```js
const assert = require('assert')
const context = {
  foo: 123
}

assert(context.foo)
assert(context.bar) // will throw an exception

// if you get to this point in the code, you know foo and bar are set.
```

**Comment by GustavoRPS** [comment]
@zeke thanks for the suggestion but it's not my intention validate the data, I only want to keep the `{{ tag }}` in the render result if the `object` used in `render` function not have the property used in the template.

`template.liquid`
```
My tag {{ some_property }}
```

`template.liquid` rendered without pass a object with `some_property`
```
My tag
```

What I want after execute `template.render({})`
```
My tag {{ some_property }}
```


I'm beginning to believe that I can not make myself understand.

**Comment by zeke** [comment]
Another way to achieve what you're describing here is to check the value before rendering the template:

```js
if (!context.some_property) {
  context.some_property = '{{ some_property }}'
}

// then render here...
```
